"""One explicit full-budget entry point. Plans never masquerade as executed plots.

Numerical source contradictions and unavailable renderers remain explicit.
Default is a read-only plan; --execute runs all original jobs, never a hidden
quick/reduced demonstration. Long original banks may take days or longer.
"""
from __future__ import annotations
import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

HERE = Path(__file__).resolve().parent
PAPERS = ["mis-communications", "mis-sensing", "rotatable-isac", "two-timescale-ma", "cooperative-satcom", "hotspot-satcom"]


def load(path):
    return json.loads(Path(path).read_text(encoding="utf-8-sig"))


def plan(paper, figure):
    inventory = load(HERE / "figure-catalog" / (paper + ".json"))
    source = next((x for x in inventory["figures"] if x["figure"] == figure), None)
    if source is None:
        raise ValueError("Figure is not in the supplied author-source inventory")
    package = HERE / paper
    result = {"paper_id": paper, "figure": figure, "original_caption": source["caption_tex"],
              "source_sha256": inventory["source_sha256"], "executed": False,
              "full_reproduction_passed": False, "automatic_downsizing": False}
    if paper.startswith("mis-"):
        mapping = load(package / "figure_map.json")
        item = next((x for x in mapping["figures"] if x["id"] == f"fig{figure}"), None)
        if item is None:
            result.update(kind="architecture_or_hardware_not_numerical_simulation", runnable=False,
                          blocker="Original hardware measurements cannot be regenerated by a simulation.")
        else:
            result.update(kind=item["kind"], runnable=True, specification=item,
                          settings=load(package / "settings.json"), executor="run.py / corresponding MATLAB engine")
            if paper == "mis-sensing" and figure in (5, 6):
                result["execution_figure"] = 3
                result["shared_bank_required"] = "exact Fig3 bank; not a new stochastic run"
    elif paper in ("rotatable-isac", "two-timescale-ma"):
        mapping = load(package / "figure_catalog.json")
        item = next((x for x in mapping["numerical_figures"] if x["figure"] == figure), None)
        if item is None:
            result.update(kind="illustration_not_simulation", runnable=False)
        else:
            result.update(kind="full_original_ensemble", runnable=True, specification=item,
                          settings=load(package / "full_config.json"), executor="figures.py / shared-input MATLAB bank")
            if paper == "two-timescale-ma" and figure in (14, 16):
                result.update(runnable=False, blocker="Original correlated-ZF matrix products/Wishart assumptions are unresolved; no substitute model.")
    else:
        mapping = load(package / "figure_coverage.json")
        chapter = 4 if paper == "cooperative-satcom" else 3
        items = [x for x in mapping["figures"] if x["source_id"] == f"{chapter}-{figure}" or x["source_id"].startswith(f"{chapter}-{figure}a") or x["source_id"].startswith(f"{chapter}-{figure}b")]
        if not items:
            raise ValueError("Original figure coverage entry is missing")
        if len(items) != 1:
            result.update(kind="multi_panel", specification=items, runnable=False,
                          blocker="Full multi-panel aggregate adapter not yet implemented; do not run one panel as the whole figure.")
            return result
        item = items[0]
        result.update(kind=item["kind"] if "kind" in item else "full_sweep", specification=item,
                      settings=load(package / "full_config.json"), executor="run.py --full / corresponding MATLAB engine",
                      runnable=figure != 1)
        if paper == "hotspot-satcom" and figure in (9, 10):
            result.update(runnable=False, blocker="Unresolved original 2D element geometry" if figure == 9 else "Original statistical-CSI SOCP is mathematically inconsistent; no substitute.")
        if not item.get("sweep_id") and result["runnable"]:
            result.update(runnable=False, blocker="Multi-output source mapping requires explicit bank selection; not silently one arbitrary curve.")
        if "*" in (item.get("sweep_id") or ""):
            result.update(runnable=False, blocker="Full multi-vs-single sub-sweep aggregate adapter not yet implemented")
        if result["runnable"] and item.get("sweep_id") not in {s["id"] for s in result["settings"]["sweeps"]}:
            result.update(runnable=False, blocker="Full original trace/sweep executor not yet implemented; no empty or replacement run")
    result["plot_readiness"] = "Only complete sensing beam/multicurve schemas currently have the unified renderer; others remain explicit WIP"
    return result


def matlab_literal(path):
    return "'" + str(Path(path).resolve()).replace("\\", "/").replace("'", "''") + "'"


def run(command):
    # Numerical parallelism is controlled, not scenario size or MC sample count.
    environment = dict(os.environ)
    environment.setdefault("PYTHONUTF8", "1")
    for name in ("OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS"):
        environment.setdefault(name, "1")
    subprocess.run(command, env=environment, check=True)


def execute(specification, language, output, matlab):
    if not specification["runnable"]:
        raise ValueError(specification.get("blocker", "This is not a numerical simulation"))
    paper, figure = specification["paper_id"], specification["figure"]
    package = HERE / paper
    output.mkdir(parents=True, exist_ok=True)
    result = output / (f"fig{figure}-{language}.json")
    config = package / ("settings.json" if paper.startswith("mis-") else "full_config.json")
    expression = None
    if paper.startswith("mis-"):
        if figure in (5, 6) and paper == "mis-sensing":
            raise ValueError("Render convergence from an existing identical Fig3 bank; no separate 6000-start run.")
        if language == "python":
            run([sys.executable, str(package / "run.py"), "--figure", f"fig{figure}", "--output", str(result)])
        else:
            function = "run_" + paper.replace("-", "_")
            expression = f"{function}({matlab_literal(result)},'fig{figure}',{matlab_literal(config)});"
    elif paper in ("rotatable-isac", "two-timescale-ma"):
        selector = (["--family", specification["specification"]["family"]] if paper == "rotatable-isac" else ["--figure", str(figure)])
        bank = output / "bank"
        run([sys.executable, str(package / "figures.py"), *selector, "--output-dir", str(bank), "--execute" if language == "python" else "--prepare"])
        if language == "matlab":
            function = "run_full_isac_figure" if paper == "rotatable-isac" else "run_full_ma_figure"
            expression = f"{function}({matlab_literal(bank/'jobs')},{matlab_literal(output/'matlab')},{matlab_literal(bank/'run_config.json')});"
        result = bank / "full_summary.json"
    else:
        sweep = specification["specification"]["sweep_id"]
        if language == "python":
            run([sys.executable, str(package / "run.py"), "--full", "--sweep", sweep, "--output", str(result)])
        else:
            function = "run_strict_" + paper.replace("-", "_")
            expression = f"{function}({matlab_literal(config)},{matlab_literal(result)},'{sweep}');"
    if expression:
        executable = matlab or shutil.which("matlab")
        if not executable:
            raise ValueError("MATLAB executable unavailable; specify --matlab. No Python-for-MATLAB substitute.")
        run([executable, "-batch", f"addpath(genpath({matlab_literal(HERE)}));{expression}exit(0,'force');"])
    if paper == "mis-sensing" and figure not in (5, 6):
        from render_figure import render
        render(result, output / "plots")
    else:
        print("Actual numerical outputs saved. The complete original figure renderer for this schema is not ready; no placeholder plot was generated.")
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--paper", choices=PAPERS, required=True)
    parser.add_argument("--figure", type=int, required=True)
    parser.add_argument("--language", choices=["python", "matlab"], default="python")
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--matlab", help="MATLAB executable path; convex packages require independently configured CVX")
    args = parser.parse_args()
    specification = plan(args.paper, args.figure)
    print(json.dumps(specification, indent=2))
    if args.execute:
        destination = args.output_dir or HERE / "outputs" / args.paper / f"fig{args.figure}-{args.language}"
        print(execute(specification, args.language, destination.resolve(), args.matlab))


if __name__ == "__main__":
    main()
