"""One explicit full-budget entry point. Plans never masquerade as executed plots.

Numerical source contradictions and unavailable renderers remain explicit.
Default is a read-only plan; --execute runs all original jobs, never a hidden
quick/reduced demonstration. Long original banks may take days or longer.
"""
from __future__ import annotations
import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

HERE = Path(__file__).resolve().parent
PAPERS = ["mis-communications", "mis-sensing", "rotatable-isac", "two-timescale-ma", "cooperative-satcom", "hotspot-satcom"]


def load(path):
    return json.loads(Path(path).read_text(encoding="utf-8-sig"))


def plan(paper, figure, settings_path=None):
    inventory = load(HERE / "figure-catalog" / (paper + ".json"))
    source = next((x for x in inventory["figures"] if x["figure"] == figure), None)
    if source is None:
        raise ValueError("Figure is not in the supplied author-source inventory")
    package = HERE / paper
    default_settings = package / ("spectral_config.json" if paper=="cooperative-satcom" else
                                  "statistical_validated_config.json" if paper=="hotspot-satcom" and figure==10 else
                                  "instantaneous_geometry_config.json" if paper=="hotspot-satcom" else
                                  "configs/full-ao10000-fig03-18-v2.json" if paper=="two-timescale-ma" and 3<=figure<=18 else
                                  "configs/figure19-full-axis-ao10000-fixed-mc-protocol-v2.json" if paper=="two-timescale-ma" and figure==19 else
                                  "configs/figure20-full-axis-ao10000-fixed-mc-protocol-v2.json" if paper=="two-timescale-ma" and figure==20 else
                                  "settings_corrected.json" if paper == "mis-sensing" else
                                  "settings.json" if paper == "mis-communications" else "full_config.json")
    selected_settings = Path(settings_path).resolve() if settings_path else default_settings
    result = {"paper_id": paper, "figure": figure, "original_caption": source["caption_tex"],
              "source_sha256": inventory["source_sha256"], "executed": False,
              "full_reproduction_passed": False, "automatic_downsizing": False,
              "settings_path": str(selected_settings),
              "settings": load(selected_settings),
              "original_curve_agreement_verified": False}
    if paper.startswith("mis-"):
        mapping = load(package / "figure_map.json")
        item = next((x for x in mapping["figures"] if x["id"] == f"fig{figure}"), None)
        if item is None:
            # Source captions distinguish conceptual figures1-3 from the
            # fabricated/experimental figures4-6; drawings are not missing
            # measurements and measurements must not become simulated traces.
            hardware = paper == "mis-communications" and figure in (4, 5, 6)
            result.update(kind="hardware_or_measurement_not_numerical_simulation" if hardware else
                          "architecture_illustration_not_numerical_simulation", runnable=False,
                          blocker="Original hardware measurements cannot be regenerated by a simulation." if hardware else
                          "This source figure is a conceptual illustration, not a numerical experiment.")
        else:
            result.update(kind=item["kind"], runnable=True, specification=item,
                          executor="run.py / corresponding MATLAB engine")
            result['full_plot_start_evidence_policy']='All original start summaries and required baseline banks; legacy selected-best success alone is rejected before rendering. Summary checks are not independent endpoint/source/RNG certificates.'
            result['native_central_entry_is_recorded_all_start_endpoint_wrapper']=False
            if paper == "mis-sensing":
                result["scientific_branch"] = result["settings"].get("solver_correction_id", selected_settings.stem)
                result["normalization_contract"] = result["settings"].get("normalization_contract")
                result["paper_error_correction_is_explicit"] = selected_settings.name != "settings.json"
            if paper == "mis-sensing" and figure in (5, 6):
                result["execution_figure"] = 3
                result["shared_bank_required"] = "exact Fig3 bank; not a new stochastic run"
    elif paper in ("rotatable-isac", "two-timescale-ma"):
        mapping = load(package / "figure_catalog.json")
        item = next((x for x in mapping["numerical_figures"] if x["figure"] == figure), None)
        if item is None:
            result.update(kind="illustration_not_simulation", runnable=False)
        else:
            result.update(kind="full_original_ensemble", runnable=True, specification=item,
                          executor="figures.py / shared-input MATLAB bank")
            if paper == "two-timescale-ma" and figure in (14, 16):
                result.update(scientific_branch="explicit_corrected_original_model_Schur_Laplace_Jensen",
                              executor="corrected_figures.py / run_corrected_ma_figure_matlab_source_v2",
                              printed_undefined_formula_recovered=False,
                              historical_figure_recovery_claimed=False)
            if paper=='two-timescale-ma' and figure in (19,20):
                result.update(exhaustive_objective_protocol='declared_fixed_MC_ordered_candidates_not_unique_historical_objective',
                              historical_exhaustive_objective_uniquely_recovered=False,
                              original_per_axis_grid=result['settings']['sweeps']['brute_force_points_per_axis'])
    else:
        mapping = load(package / "figure_coverage.json")
        chapter = 4 if paper == "cooperative-satcom" else 3
        items = [x for x in mapping["figures"] if x["source_id"] == f"{chapter}-{figure}" or x["source_id"].startswith(f"{chapter}-{figure}a") or x["source_id"].startswith(f"{chapter}-{figure}b")]
        if not items:
            raise ValueError("Original figure coverage entry is missing")
        result.update(kind="multi_panel" if len(items)>1 else items[0].get("kind", "full_sweep"),
                      specification=items, executor="run.py --full / corresponding MATLAB engine",
                      runnable=all(i.get("simulation_required",True) for i in items))
        sweeps=[]
        for item in items:
            identifier=item["source_id"]
            if identifier=="3-2": sweeps.append("cdf_kS20")
            elif identifier in ("3-7a","3-7b"):
                sweeps.append("cdf_kS20" if identifier=="3-7a" else "cdf_kS10")
                result["caption_conflict"]="filename Rician interpretation is explicit; caption/filename swap is not uniquely resolved"
            elif identifier=="3-10":
                result.update(scientific_branch="explicit_corrected_vector_QT_original_finite_Rician_model",
                              executor="run_statistical_validated.py / run_strict_hotspot_statistical_validated",
                              printed_invalid_SOC_recovered=False)
                result['uniform_all_scheme_initialization_policy']=result['settings'].get('initialization_ensemble')
                result['all_original_source_constraints_verified']=False
                sweeps.append("statistical")
            elif identifier=="4-11":
                for beta in (20,0):
                    sweeps.append(f"multi_vs_single_multi_kL{beta}")
                    sweeps.extend(f"multi_vs_single_single_{offset}_kL{beta}" for offset in (1.25,2.5))
            elif item.get("sweep_id"): sweeps.append(item["sweep_id"])
        result["execution_sweeps"]=list(dict.fromkeys(sweeps))
        if paper=='hotspot-satcom':
            result['geometry_contract']=result['settings'].get('geometry_contract')
            result['historical_author_coordinates_recovered']=False
            result['old_radius15_source_spacing_violation_is_preserved_not_reused']=True
        if paper=="hotspot-satcom" and figure==9:
            result.update(executor="hotspot_element_count.py / run_hotspot_element_count_matlab",
                          scientific_branch="original_count_only_aperture_gain_with_declared_frozen_unreported_centers",
                          original_author_center_geometry_recovered=False,row_column_factorization_inferred=False,
                          effective_execution_parameter_overrides={"U":6,"K":10,"M":25,"N":16,"J":16,
                              "kappa_satellite_db":12,"reference_elements_per_subsurface":28000},
                          effective_execution_grid=list(items[0]["x"]["values"]),
                          independent_channel_realizations_per_count=1000,
                          full_required_channel_realizations=7000,
                          base_settings_shape_pairs_are_not_the_effective_count_grid=True,
                          effective_configuration_comparison="Existing byte-bound full_count_configuration override; metadata only, no numerical model or execution change")
        if result["runnable"] and not sweeps:
            result.update(runnable=False,blocker="No validated numerical sweep exists for this illustration")
    result["plot_readiness"] = "Complete-bank source-mapped renderer available; partial, capped, changed-source banks are rejected"
    return result


def matlab_literal(path):
    return "'" + str(Path(path).resolve()).replace("\\", "/").replace("'", "''") + "'"


def corrected_ma_matlab_call(bank, output):
    """Bind corrected evaluation to the actual full-v2 MATLAB trajectory schema.

    The durable source runner must finish before the corrected adapter checks
    all300 required cases. Old startup-error/source-v1 files are not upgraded.
    """
    source = output / 'matlab'
    corrected = output / 'matlab-corrected'
    adapter = HERE / 'matlab-corrected-source-v2'
    return (f"run_matlab_bank_checked('two-timescale-ma',{matlab_literal(bank)},{matlab_literal(source)});"
            f"addpath({matlab_literal(adapter)});"
            f"run_corrected_ma_figure_matlab_source_v2({matlab_literal(bank/'jobs')},"
            f"{matlab_literal(source)},{matlab_literal(corrected)},"
            f"{matlab_literal(bank/'run_config.json')},false);")


def statistical_matlab_call(config,output,result):
    package=HERE/'hotspot-satcom'
    names={'statistical_validated_config.json':'run_strict_hotspot_statistical_validated',
           'statistical_geometry_config.json':'run_strict_hotspot_statistical_geometry',
           'spectral_config.json':'run_strict_hotspot_statistical_spectral',
           'full_config.json':'run_strict_hotspot_statistical_controlled'}
    if config.name not in names or config.resolve()!=(package/config.name).resolve():
        raise ValueError('Statistical runners bind frozen canonical configurations in both languages')
    if config.name=='statistical_validated_config.json':
        bank=output/'checkpoints'/'statistical'/'matlab'
        return f"run_hotspot_validated_bank_checked({matlab_literal(config)},{matlab_literal(bank)});",bank/'full18-matlab.json'
    return f"{names[config.name]}({matlab_literal(config)},{matlab_literal(result)},'full');",result


def run(command):
    # Numerical parallelism is controlled, not scenario size or MC sample count.
    environment = dict(os.environ)
    environment.setdefault("PYTHONUTF8", "1")
    for name in ("OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS"):
        environment.setdefault(name, "1")
    subprocess.run(command, env=environment, check=True)


def execute(specification, language, output, matlab, source_result=None, workers=1, source_bank=None):
    if not specification["runnable"]:
        raise ValueError(specification.get("blocker", "This is not a numerical simulation"))
    paper, figure = specification["paper_id"], specification["figure"]
    package = HERE / paper
    output.mkdir(parents=True, exist_ok=True)
    result = output / (f"fig{figure}-{language}.json")
    config = Path(specification["settings_path"])
    expression = None
    if paper.startswith("mis-"):
        if figure in (5, 6) and paper == "mis-sensing":
            if source_result is None:
                raise ValueError('Provide --source-result containing the actual complete Fig3 bank; never launch a different6000-start convergence run')
            from render_figure import render
            render(source_result,output/'plots',figure=figure)
            return source_result
        if language == "python":
            if paper=="mis-communications":
                bank=source_bank or output/"bank"
                run([sys.executable,str(HERE/"execute_mis_communications.py"),"--figure",f"fig{figure}",
                     "--bank",str(bank),"--workers",str(workers),"--settings",str(config)])
                result=bank/"full-result-python.json"
            else:
                if figure in (3,4):
                    bank=source_bank or output/"bank"
                    run([sys.executable,str(HERE/"execute_mis_sensing.py"),"--figure",f"fig{figure}",
                         "--bank",str(bank),"--workers",str(workers),"--settings",str(config)])
                    result=bank/"full-result-python.json"
                else:
                    run([sys.executable, str(package / "run.py"), "--figure", f"fig{figure}",
                         "--settings",str(config),"--output", str(result)])
        else:
            function = "run_" + paper.replace("-", "_")
            expression = f"{function}({matlab_literal(result)},'fig{figure}',{matlab_literal(config)});"
    elif paper in ("rotatable-isac", "two-timescale-ma"):
        selector = (["--family", specification["specification"]["family"]] if paper == "rotatable-isac" else ["--figure", str(figure)])
        bank = source_bank or output / "bank"
        if not (bank/"manifest.json").exists():
            run([sys.executable, str(package / "figures.py"), *selector, "--config",str(config),"--output-dir", str(bank), "--prepare"])
        actual_plan=load(bank/"plan.json")
        if (bank/"run_config.json").read_bytes()!=config.read_bytes():
            raise ValueError('Selected immutable bank configuration differs; no overwrite/mixed-configuration run')
        if (paper=="rotatable-isac" and actual_plan.get("family")!=specification["specification"]["family"]
            or paper=="two-timescale-ma" and actual_plan.get("figure")!=figure):
            raise ValueError('Selected immutable bank is for a different original figure/family')
        # Durable execution checks immutable sources/configuration and every job.
        if language=="python":
            if paper=="two-timescale-ma" and figure in (14,16):
                run([sys.executable,str(package/"corrected_figures.py"),"--bank",str(bank),
                     "--execute","--workers",str(workers),"--output-dir",str(output/"plots")])
                return output/"plots"/"derivation-summary.json"
            run([sys.executable,str(package/"execute_bank.py"),"--bank",str(bank),"--workers",str(workers)])
        if language == "matlab":
            expression = f"run_matlab_bank_checked('{paper}',{matlab_literal(bank)},{matlab_literal(output/'matlab')});"
            if paper=="two-timescale-ma" and figure in (14,16):
                expression=corrected_ma_matlab_call(bank,output)
        result = bank / "full_summary.json"
    else:
        results=[]
        for sweep in specification["execution_sweeps"]:
            result=output/f"{sweep}-{language}.json";results.append(result)
            if language=="python":
                if sweep=="statistical":
                    validated=config.resolve()==(package/"statistical_validated_config.json").resolve()
                    compliant=config.resolve()==(package/"statistical_geometry_config.json").resolve()
                    spectral=config.resolve()==(package/"spectral_config.json").resolve()
                    if not validated and not compliant and not spectral and config.resolve()!=(package/"full_config.json").resolve():
                        raise ValueError('Statistical runners bind frozen configs; alternate configuration is not silently ignored')
                    command=[sys.executable,str(package/("run_statistical_validated.py" if validated else "run_statistical_geometry.py" if compliant else "run_statistical_spectral.py" if spectral else "run_statistical_controlled.py")),"--full"]
                elif paper=="hotspot-satcom" and figure==9:
                    command=[sys.executable,str(HERE/"hotspot_element_count.py"),"--config",str(config)]
                elif paper=="cooperative-satcom" and config.resolve()==(package/"spectral_config.json").resolve():
                    command=[sys.executable,str(package/"run_cooperative_guarded.py"),"--full","--sweep",sweep]
                elif paper=="hotspot-satcom" and config.resolve()==(package/"instantaneous_geometry_config.json").resolve():
                    command=[sys.executable,str(package/"run_instantaneous_geometry.py"),"--full","--sweep",sweep]
                else:command=[sys.executable,str(package/"run.py"),"--full","--sweep",sweep,"--config",str(config)]
                run([*command,"--checkpoint-dir",str(output/"checkpoints"/sweep),"--output",str(result)])
            else:
                if sweep=="statistical":
                    expression,result=statistical_matlab_call(config,output,result)
                    results[-1]=result;run_matlab(expression,matlab);continue
                elif paper=="hotspot-satcom" and figure==9:function="run_hotspot_element_count_matlab"
                elif paper=="cooperative-satcom" and config.name=="spectral_config.json":function="run_strict_cooperative_guarded"
                elif paper=="hotspot-satcom" and config.name=="instantaneous_geometry_config.json":function="run_strict_hotspot_instantaneous_geometry"
                else:function="run_strict_"+paper.replace("-","_")
                scope="full" if sweep=="statistical" else sweep
                expression=f"{function}({matlab_literal(config)},{matlab_literal(result)},'{scope}');"
                run_matlab(expression,matlab)
        from render_satellite_figures import aggregate,render
        data=aggregate(paper,figure,[load(r) for r in results]);render(data,output/"plots")
        return results
    if expression:
        run_matlab(expression,matlab)
    if paper.startswith('mis-'):
        from render_figure import render
        render(result, output / "plots")
    elif language=="python":
        run([sys.executable,str(package/"render_figures.py"),"--bank",str(bank),"--output-dir",str(output/"plots")])
    elif paper=='two-timescale-ma' and figure in (14,16):
        return output/'matlab-corrected'/'derivation-summary-matlab.json'
    else:
        run([sys.executable,str(HERE/'render_matlab_bank.py'),'--paper',paper,'--bank',str(bank),
             '--results',str(output/'matlab'),'--output-dir',str(output/'plots')])
    return result


def run_matlab(expression,matlab):
    executable=matlab or shutil.which("matlab")
    if not executable:raise ValueError("MATLAB executable unavailable; specify --matlab. No Python-for-MATLAB substitute.")
    run([executable,"-batch",f"maxNumCompThreads(1);addpath(genpath({matlab_literal(HERE)}));{expression}exit(0,'force');"])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--paper", choices=PAPERS, required=True)
    artifact = parser.add_mutually_exclusive_group(required=True)
    artifact.add_argument("--figure", type=int)
    artifact.add_argument("--table", type=int, help="Source-qualified parameter-table plan/audit, never an optimizer")
    parser.add_argument("--language", choices=["python", "matlab"], default="python")
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--matlab", help="MATLAB executable path; convex packages require independently configured CVX")
    parser.add_argument('--source-result',type=Path,help='Exact complete Fig3 output reused for sensing convergence Figs5/6')
    parser.add_argument('--source-bank',type=Path,help='Existing immutable complete input bank; never regenerate/overwrite its inputs')
    parser.add_argument('--settings',type=Path,help='Explicit scientific settings, including preserved printed or inferred normalization branches')
    parser.add_argument('--workers',type=int,default=1,choices=[1,2,3],help='CPU parallelism only; all scenario populations and budgets remain full')
    args = parser.parse_args()
    if args.table is not None:
        from table_reproduction import table_plan, execute_table
        if args.settings or args.source_result or args.source_bank:
            parser.error("Parameter-table audits bind canonical source evidence; figure overrides are not table inputs")
        specification = table_plan(args.paper, args.table)
        print(json.dumps(specification, indent=2))
        if args.execute:
            destination = args.output_dir or HERE / "outputs" / args.paper / f"table{args.table}-parameter-audit"
            print(execute_table(specification, args.language, destination.resolve()))
        return
    specification = plan(args.paper, args.figure,args.settings)
    print(json.dumps(specification, indent=2))
    if args.execute:
        destination = args.output_dir or HERE / "outputs" / args.paper / f"fig{args.figure}-{args.language}"
        print(execute(specification, args.language, destination.resolve(), args.matlab,args.source_result,args.workers,args.source_bank))


if __name__ == "__main__":
    main()
