/* MIS demonstrator: all plots use one shared scalar complex aperture model. */
(() => {
'use strict';
const D=window.MIS_DATA,$=id=>document.getElementById(id),TAU=2*Math.PI,rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI;
if(!D){$('loading').textContent='相位数据未加载。请使用完整演示文件夹打开。';return;}
const C=D.config,N=C.n1||16,n=C.n2||12,M=N*N,pitch=C.pitchMm/(C.wavelengthMm||299.792458/C.frequencyGHz);
const COLORS={fg:'#cad8e8',muted:'#849bb4',grid:'#223448',cyan:'#63e4d5',amber:'#ffc47b',bg:'#0b1623'};
const state={method:'optimized',sx:0,sy:0,az:30,el:0,snrRef:26,mod:16,equalized:true,gap:3.2,showBeam:true,tour:false};
const x=new Float64Array(M),y=new Float64Array(M);for(let r=0;r<N;r++)for(let c=0;c<N;c++){let i=r*N+c;x[i]=(c-(N-1)/2)*pitch;y[i]=(r-(N-1)/2)*pitch;}
const dir=(az,el)=>({ux:Math.sin(rad(az))*Math.cos(rad(el)),uy:Math.sin(rad(el)),uz:Math.cos(rad(az))*Math.cos(rad(el))});
const db=p=>10*Math.log10(Math.max(p,1e-14));const posIndex=(sx,sy)=>(sy+2)*5+sx+2;
const caches=new Map(); let scene=null,last={},renderQueued=false,tourTimer=null,toastTimer=null,storyTimer=null,storyStep=0;
function aperture(method,sx,sy){
 const key=method+':'+sx+','+sy;if(caches.has(key))return caches.get(key);
 const d=D[method],phase=Float64Array.from(d.phi1),re=new Float64Array(M),im=new Float64Array(M),off=(N-n)/2;
 for(let r=0;r<n;r++)for(let c=0;c<n;c++){const ix=c+off+sx,iy=r+off+sy;if(ix>=0&&ix<N&&iy>=0&&iy<N)phase[iy*N+ix]+=d.phi2[r*n+c];}
 for(let i=0;i<M;i++){phase[i]=((phase[i]%TAU)+TAU)%TAU;re[i]=Math.cos(phase[i]);im[i]=Math.sin(phase[i]);}
 const out={phase,re,im};caches.set(key,out);return out;
}
function field(ap,ux,uy){let re=0,im=0;for(let i=0;i<M;i++){const a=-TAU*(x[i]*ux+y[i]*uy),c=Math.cos(a),s=Math.sin(a);re+=ap.re[i]*c-ap.im[i]*s;im+=ap.re[i]*s+ap.im[i]*c;}re/=M;im/=M;return{re,im,power:re*re+im*im};}
function bestPosition(method,az,el){const u=dir(az,el);let best={power:-1,index:0,x:0,y:0};for(let sy=-2;sy<=2;sy++)for(let sx=-2;sx<=2;sx++){let h=field(aperture(method,sx,sy),u.ux,u.uy);if(h.power>best.power)best={...h,index:posIndex(sx,sy),x:sx,y:sy};}return best;}
function makeBeam(ap){if(ap.beam)return ap.beam;const rows=25,cols=37,vertices=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){let u=dir(-85+170*c/(cols-1),-85+170*r/(rows-1));vertices.push({...u,power:field(ap,u.ux,u.uy).power});}return ap.beam={vertices,rows,cols};}
function seedRandom(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function symbols(h){const q=Math.sqrt(state.mod),norm=Math.sqrt(2*(state.mod-1)/3),rand=seedRandom(20261005),samples=[],ideal=[],sigma=Math.sqrt(10**(-state.snrRef/10)/2);let errs=0,bitErrs=0,errPower=0,symPower=0;const bits=Math.log2(state.mod),popcount=a=>{let count=0;for(;a;a>>>=1)count+=a&1;return count;};for(let a=0;a<q;a++)for(let b=0;b<q;b++)ideal.push({re:(2*a-q+1)/norm,im:(2*b-q+1)/norm});
 for(let i=0;i<768;i++){const ai=Math.floor(rand()*q),bi=Math.floor(rand()*q),sr=(2*ai-q+1)/norm,si=(2*bi-q+1)/norm,z=Math.sqrt(-2*Math.log(Math.max(1e-12,rand()))),t=TAU*rand(),nr=z*Math.cos(t)*sigma,ni=z*Math.sin(t)*sigma,yr=h.re*sr-h.im*si+nr,yi=h.re*si+h.im*sr+ni,p=Math.max(h.power,1e-16),er=(yr*h.re+yi*h.im)/p,ei=(yi*h.re-yr*h.im)/p;
 const ar=Math.max(0,Math.min(q-1,Math.round((er*norm+q-1)/2))),br=Math.max(0,Math.min(q-1,Math.round((ei*norm+q-1)/2)));if(ar!==ai||br!==bi)errs++;bitErrs+=popcount((ar^(ar>>1))^(ai^(ai>>1)))+popcount((br^(br>>1))^(bi^(bi>>1)));errPower+=(er-sr)**2+(ei-si)**2;symPower+=sr*sr+si*si;samples.push({re:state.equalized?er:yr,im:state.equalized?ei:yi});}
 return{samples,ideal,evm:Math.sqrt(errPower/symPower),ber:bitErrs/(768*bits),ser:errs/768,bitErrs,bits:768*bits};
}
function canvas(id){const el=$(id),rect=el.getBoundingClientRect(),w=Math.max(50,rect.width),h=Math.max(50,rect.height),dpr=Math.min(window.devicePixelRatio||1,2);if(el.width!==Math.round(w*dpr)||el.height!==Math.round(h*dpr)){el.width=Math.round(w*dpr);el.height=Math.round(h*dpr);}const ctx=el.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.font='10px "Segoe UI", "Microsoft YaHei", sans-serif';return{el,ctx,w,h};}
function text(ctx,s,x,y,color=COLORS.muted,align='left'){ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(s,x,y);}
function graph(id,xmin,xmax,ymin,ymax,xticks,yticks){const {ctx,w,h}=canvas(id),m={l:49,r:17,t:21,b:37},ww=w-m.l-m.r,hh=h-m.t-m.b,X=v=>m.l+(v-xmin)/(xmax-xmin)*ww,Y=v=>m.t+(ymax-v)/(ymax-ymin)*hh;ctx.lineWidth=1;for(let v of yticks){ctx.strokeStyle=COLORS.grid;ctx.beginPath();ctx.moveTo(m.l,Y(v));ctx.lineTo(w-m.r,Y(v));ctx.stroke();text(ctx,String(v),m.l-8,Y(v)+3,COLORS.muted,'right');}for(let v of xticks){ctx.strokeStyle=COLORS.grid;ctx.beginPath();ctx.moveTo(X(v),m.t);ctx.lineTo(X(v),h-m.b);ctx.stroke();text(ctx,String(v),X(v),h-m.b+17,COLORS.muted,'center');}return{ctx,w,h,m,X,Y,ww,hh};}
function line(g,points,color,width=2){g.ctx.save();g.ctx.beginPath();g.ctx.rect(g.m.l,g.m.t,g.ww,g.hh);g.ctx.clip();g.ctx.strokeStyle=color;g.ctx.lineWidth=width;g.ctx.beginPath();points.forEach((p,i)=>i?g.ctx.lineTo(g.X(p[0]),g.Y(p[1])):g.ctx.moveTo(g.X(p[0]),g.Y(p[1])));g.ctx.stroke();g.ctx.restore();}
function phaseMap(id,ph,size,outline){const {ctx,w,h,el}=canvas(id),side=Math.min(w-16,h-12),cell=side/size,ox=(w-side)/2,oy=(h-side)/2;for(let r=0;r<size;r++)for(let c=0;c<size;c++){let a=((ph[r*size+c]%TAU)+TAU)%TAU;ctx.fillStyle=`hsl(${a/TAU*360},72%,62%)`;ctx.fillRect(ox+c*cell,oy+(size-1-r)*cell,Math.max(.5,cell-1),Math.max(.5,cell-1));}if(outline){ctx.strokeStyle='#ffffff';ctx.lineWidth=1.5;ctx.strokeRect(ox+((N-n)/2+state.sx)*cell,oy+(N-(N-n)/2-state.sy-n)*cell,n*cell,n*cell);}el._phaseHit={ph,size,cell,ox,oy};}
function beamPlot(){const g=graph('beamChart',-80,80,-45,0,[-60,-30,0,30,60],[-40,-30,-20,-10,0]);for(let method of ['snell','optimized']){let ap=aperture(method,state.sx,state.sy);const key='cut'+state.el;let points=ap[key];if(!points){points=[];for(let az=-80;az<=80;az+=.5){let u=dir(az,state.el);points.push([az,db(field(ap,u.ux,u.uy).power)]);}ap[key]=points;}line(g,points,method==='optimized'?COLORS.cyan:COLORS.amber,method===state.method?2.3:1.3);}g.ctx.setLineDash([4,4]);g.ctx.strokeStyle='#bfcedc';g.ctx.beginPath();g.ctx.moveTo(g.X(state.az),g.m.t);g.ctx.lineTo(g.X(state.az),g.Y(-45));g.ctx.stroke();g.ctx.setLineDash([]);text(g.ctx,'相干效率 (dB)',g.m.l,11);text(g.ctx,'方位角 (°)',g.w/2,g.h-3,COLORS.muted,'center');text(g.ctx,'Rx',Math.min(g.w-30,g.X(state.az)+5),g.m.t+12,COLORS.fg);$('cutEl').textContent=`EL ${state.el}°`;
 const c=C.snellC??Math.sin(rad(35))/(2*pitch),ux=c*state.sx*pitch,uy=c*state.sy*pitch,az=deg(Math.atan2(ux,Math.sqrt(Math.max(0,1-ux*ux-uy*uy)))),el=deg(Math.asin(uy));$('snellPrediction').textContent=`Snell 重叠区解析方向：az ${az.toFixed(1)}° / el ${el.toFixed(1)}°。整面辐射还包含未覆盖单元的贡献。`;
}
function constellationPlot(s){const {ctx,w,h}=canvas('constellation'),side=Math.min(w-68,h-45),ox=(w-side)/2,oy=17,limit=state.equalized?1.85:1.35,X=v=>ox+(v+limit)/(2*limit)*side,Y=v=>oy+(limit-v)/(2*limit)*side;ctx.strokeStyle=COLORS.grid;ctx.lineWidth=1;for(let v of [-1,-.5,0,.5,1]){ctx.beginPath();ctx.moveTo(X(v),oy);ctx.lineTo(X(v),oy+side);ctx.stroke();ctx.beginPath();ctx.moveTo(ox,Y(v));ctx.lineTo(ox+side,Y(v));ctx.stroke();text(ctx,String(v),X(v),oy+side+15,COLORS.muted,'center');text(ctx,String(v),ox-7,Y(v)+3,COLORS.muted,'right');}ctx.save();ctx.beginPath();ctx.rect(ox,oy,side,side);ctx.clip();let clipped=0;ctx.fillStyle='#63e4d599';for(let p of s.samples){if(Math.abs(p.re)>limit||Math.abs(p.im)>limit)clipped++;ctx.beginPath();ctx.arc(X(p.re),Y(p.im),1.7,0,TAU);ctx.fill();}ctx.strokeStyle=COLORS.amber;ctx.lineWidth=1.1;for(let p of s.ideal){let a=X(p.re),b=Y(p.im);ctx.beginPath();ctx.moveTo(a-4,b);ctx.lineTo(a+4,b);ctx.moveTo(a,b-4);ctx.lineTo(a,b+4);ctx.stroke();}ctx.restore();text(ctx,'Q',ox-13,11);text(ctx,'I',ox+side+8,oy+side+3);$('constellationNote').textContent=`768 个仿真符号 · 固定随机种子${clipped?' · 视窗外 '+clipped+' 点':''} · ${state.equalized?'已除以复信道 F':'原始 y = Fs + n，理想点为发射星座'}`;}
function coverage(){const rows=D.targets.map((t,i)=>({target:t,opt:D.optimized.targetPower[i],snell:D.snell.targetPower[i]})),all=rows.flatMap(r=>[state.snrRef+db(r.opt),state.snrRef+db(r.snell)]),lo=Math.floor((Math.min(...all)-2)/5)*5,hi=Math.ceil((Math.max(...all)+2)/5)*5,ticks=[];for(let q=lo;q<=hi;q+=5)ticks.push(q);const g=graph('coverageChart',.4,9.6,lo,hi,[1,2,3,4,5,6,7,8,9],ticks);line(g,rows.map((r,i)=>[i+1,state.snrRef+db(r.snell)]),COLORS.amber,1.5);line(g,rows.map((r,i)=>[i+1,state.snrRef+db(r.opt)]),COLORS.cyan,2);for(let method of ['opt','snell'])for(let i=0;i<9;i++){g.ctx.fillStyle=method==='opt'?COLORS.cyan:COLORS.amber;g.ctx.beginPath();g.ctx.arc(g.X(i+1),g.Y(state.snrRef+db(rows[i][method])),3,0,TAU);g.ctx.fill();}text(g.ctx,'SNR (dB)',g.m.l,11);text(g.ctx,'目标 1–9：仰角分组 −20° / 0° / +20°，各组方位 −30° / 0° / +30°',g.w/2,g.h-2,COLORS.muted,'center');$('optWorst').textContent=(state.snrRef+db(D.optimized.score)).toFixed(2)+' dB';$('snellWorst').textContent=(state.snrRef+db(D.snell.score)).toFixed(2)+' dB';$('improvement').textContent='+'+(db(D.optimized.score)-db(D.snell.score)).toFixed(2)+' dB';}
function convergence(){const hist=D.history||D.optimized.history||[],values=hist.map((v,i)=>[v.iteration??i,db(v.score??v)]);if(!values.length){$('convergenceNote').textContent='请查看计算目录中的离线优化记录。';return;}const min=Math.floor(Math.min(...values.map(v=>v[1]))-1),max=Math.ceil(Math.max(...values.map(v=>v[1]))+1),end=Math.max(...values.map(v=>v[0])),ticks=[];for(let v=min;v<=max;v+=Math.max(1,Math.ceil((max-min)/5)))ticks.push(v);const g=graph('convergenceChart',0,end,min,max,[0,Math.round(end/4),Math.round(end/2),Math.round(end*3/4),end],ticks);line(g,values,COLORS.cyan,2);text(g.ctx,'最差方向相干效率 (dB)',g.m.l,11);text(g.ctx,'累计记录步',g.w/2,g.h-2,COLORS.muted,'center');$('convergenceNote').textContent='记录当前已找到的最佳可行解；目标为 9 个方向中各自最优位置功率的最小值。两层相位均在离线阶段联合设计。包含 Snell 初值及多起点搜索，结果不代表全局最优。';}
function update(){renderQueued=false;const ap=aperture(state.method,state.sx,state.sy),u=dir(state.az,state.el),h=field(ap,u.ux,u.uy),s=symbols(h);last={h,s,ap};$('shiftX').value=state.sx;$('shiftY').value=state.sy;$('shiftXOut').textContent=`${state.sx*6} mm · ${state.sx} 格`;$('shiftYOut').textContent=`${state.sy*6} mm · ${state.sy} 格`;$('azimuth').value=state.az;$('elevation').value=state.el;$('azOut').textContent=state.az+'°';$('elOut').textContent=state.el+'°';$('snrOut').textContent=state.snrRef+' dB';$('positionId').textContent='P'+String(posIndex(state.sx,state.sy)+1).padStart(2,'0');$('snrValue').innerHTML=(state.snrRef+db(h.power)).toFixed(1)+'<em>dB</em>';$('powerValue').textContent='相干效率 '+(100*h.power).toFixed(2)+'%';$('evmValue').innerHTML=(100*s.evm).toFixed(1)+'<em>%</em>';$('berValue').textContent=s.ber===0?'0':s.ber.toExponential(1);$('bitsValue').textContent=s.bitErrs+' / '+s.bits+' 比特错误';$('worstValue').innerHTML=(state.snrRef+db(D[state.method].score)).toFixed(1)+'<em>dB</em>';
 for(const method of ['optimized','snell']){let b=$(method+'Btn');b.classList.toggle('selected',method===state.method);b.setAttribute('aria-pressed',String(method===state.method));}
 $('methodNote').textContent=state.method==='optimized'?'已载入离线联合优化相位。仅机械位置变化；两层单元相位保持固定。':'互补二次相位由 Snell 定律解析生成。层间位移在重叠区域产生线性相位梯度。';
 document.querySelectorAll('#positionGrid button').forEach(b=>{const active=+b.dataset.x===state.sx&&+b.dataset.y===state.sy;b.classList.toggle('current',active);b.setAttribute('aria-pressed',String(active));});
 phaseMap('phase1',D[state.method].phi1,N,true);phaseMap('phase2',D[state.method].phi2,n,false);phaseMap('phaseEffective',ap.phase,N,true);beamPlot();constellationPlot(s);coverage();
 if(scene)scene.update({phi1:D[state.method].phi1,phi2:D[state.method].phi2,phaseEffective:Array.from(ap.phase),shiftX:state.sx,shiftY:state.sy,beam:makeBeam(ap),receiver:u,gap:state.gap,showBeam:state.showBeam,showWaves:true,showPhases:true,layerVisible:true});
}
function scheduleUpdate(){if(!renderQueued){renderQueued=true;requestAnimationFrame(update);}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2700);}
function stopTour(){if(tourTimer)clearInterval(tourTimer);if(storyTimer)clearTimeout(storyTimer);storyTimer=null;tourTimer=null;state.tour=false;$('tourBtn').classList.remove('running');$('tourBtn').textContent='▶ 自动演示 9 个目标方向';$('storyBtn').classList.remove('running');$('storyBtn').textContent='▶ 对准 → 失配 → 恢复';}
function match(){const b=bestPosition(state.method,state.az,state.el);state.sx=b.x;state.sy=b.y;scheduleUpdate();return b;}
for(let sy=2;sy>=-2;sy--)for(let sx=-2;sx<=2;sx++){const b=document.createElement('button');b.dataset.x=sx;b.dataset.y=sy;b.textContent=posIndex(sx,sy)+1;b.title=`X ${sx*6} mm / Y ${sy*6} mm`;b.setAttribute('aria-label',`机械位置 ${posIndex(sx,sy)+1}：X ${sx*6} 毫米，Y ${sy*6} 毫米`);b.onclick=()=>{stopTour();state.sx=sx;state.sy=sy;scheduleUpdate();};$('positionGrid').appendChild(b);}
for(let [id,key] of [['shiftX','sx'],['shiftY','sy'],['azimuth','az'],['elevation','el'],['snrRef','snrRef']])$(id).addEventListener('input',e=>{stopTour();state[key]=+e.target.value;scheduleUpdate();});
for(let method of ['optimized','snell'])$(method+'Btn').onclick=()=>{state.method=method;scheduleUpdate();toast('已切换静态设计；机械位置保持为当前格点。');};
 $('matchBtn').onclick=()=>{stopTour();const b=match();toast('已枚举 25 个位置，选择 P'+(b.index+1)+'。');};
 $('modulation').onchange=e=>{state.mod=+e.target.value;scheduleUpdate();};$('equalizer').onchange=e=>{state.equalized=e.target.value==='equalized';scheduleUpdate();};$('gap').oninput=e=>{state.gap=+e.target.value;scheduleUpdate();};$('beamBtn').onclick=()=>{state.showBeam=!state.showBeam;$('beamBtn').classList.toggle('active',state.showBeam);$('beamBtn').setAttribute('aria-pressed',String(state.showBeam));scheduleUpdate();};$('resetCamera').onclick=()=>scene?.resetCamera();
 $('tourBtn').onclick=()=>{if(state.tour){stopTour();return;}stopTour();state.tour=true;let i=0;const step=()=>{const t=D.targets[i++%D.targets.length];state.az=t.az;state.el=t.el;match();};step();tourTimer=setInterval(step,2300);$('tourBtn').classList.add('running');$('tourBtn').textContent='Ⅱ 暂停自动演示';};
 $('storyBtn').onclick=()=>{if(storyTimer){stopTour();return;}stopTour();storyStep=0;const step=()=>{if(storyStep===0){state.az=0;state.el=0;match();$('storyBtn').textContent='Ⅰ 对准：接收机位于 0°';toast('第 1 步：接收机与机械选定波束对准。');}else if(storyStep===1){state.az=30;scheduleUpdate();$('storyBtn').textContent='Ⅱ 失配：接收机移到 30°';toast('第 2 步：只改变接收机方向，机械位置不变。');}else{match();$('storyBtn').textContent='Ⅲ 恢复：仅移动第二层';toast('第 3 步：静态相位保持不变，移动 MS 2 恢复链路。');}storyStep++;$('storyBtn').classList.add('running');if(storyStep<3)storyTimer=setTimeout(step,3500);else storyTimer=setTimeout(()=>{storyTimer=null;$('storyBtn').classList.remove('running');$('storyBtn').textContent='▶ 对准 → 失配 → 恢复';},3500);};step();};
 $('mobileControls').onclick=()=>{const open=document.querySelector('.controls').classList.toggle('expanded');$('mobileControls').setAttribute('aria-expanded',String(open));$('mobileControls').innerHTML=(open?'收起参数，查看空间与信号':'展开设计、位置与通信参数')+' <span>'+ (open?'⌃':'⌄')+'</span>';};
 $('layoutBtn').onclick=()=>{const compact=document.body.classList.toggle('presentation');$('layoutBtn').textContent=compact?'展开讲解布局 ↗':'并排演示布局 ↗';requestAnimationFrame(scheduleUpdate);};$('gap').value=state.gap;
 $('aboutBtn').onclick=()=>$('aboutDialog').showModal();$('convergenceBtn').onclick=()=>{$('convergenceDialog').showModal();requestAnimationFrame(convergence);};document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
 for(let id of ['phase1','phase2','phaseEffective'])$(id).onmousemove=e=>{const p=$(id)._phaseHit;if(!p)return;const r=$(id).getBoundingClientRect(),cx=Math.floor((e.clientX-r.left-p.ox)/p.cell),cy=p.size-1-Math.floor((e.clientY-r.top-p.oy)/p.cell);if(cx>=0&&cx<p.size&&cy>=0&&cy<p.size){const a=((p.ph[p.size*cy+cx]%TAU)+TAU)%TAU;$('phaseTip').textContent=`${id==='phase1'?'MS 1':id==='phase2'?'MS 2':'等效相位'} · 列 ${cx+1} / 行 ${cy+1} · ${deg(a).toFixed(1)}° = ${a.toFixed(3)} rad；白框标记 MS 2 的覆盖区域。`;}};
 $('exportBtn').onclick=()=>{const payload={createdAt:new Date().toISOString(),type:'model-driven-simulation',state:{...state},config:C,staticPhases:{phi1:D[state.method].phi1,phi2:D[state.method].phi2},effectivePhase:Array.from(last.ap.phase),channel:last.h,metrics:{snrDb:state.snrRef+db(last.h.power),evm:last.s.evm,ber:last.s.ber,bits:last.s.bits,bitErrors:last.s.bitErrs},scope:'Uniform plane-wave illumination; tight-stack padding model; scalar AWGN; not measured or calibrated hardware data.'};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`MIS-${state.method}-P${posIndex(state.sx,state.sy)+1}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出相位、位置、复信道和本帧指标。');};
 try{if(window.createMISScene){scene=window.createMISScene($('scene'));$('loading')?.remove();}else throw new Error('3D renderer missing');}catch(e){$('loading').textContent='3D 视图暂不可用：'+e.message+'。相位图和链路计算仍可使用。';console.error(e);}
 window.addEventListener('resize',scheduleUpdate);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.tour)stopTour();});
 window.MIS_APP={getState:()=>({...state}),getMetrics:()=>({h:last.h,evm:last.s?.evm,ber:last.s?.ber,bits:last.s?.bits}),field:(method,sx,sy,az,el)=>{let u=dir(az,el);return field(aperture(method,sx,sy),u.ux,u.uy);},bestPosition,getEffectivePhase:(method,sx,sy)=>Array.from(aperture(method,sx,sy).phase),getStaticPhases:method=>({phi1:D[method].phi1.slice(),phi2:D[method].phi2.slice()})};
 match();update();
})();
